[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught (in promise) Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 34, columns 9--22) Array entry 1 with value \u001B[34mlight: flatly\u001B[39m failed to be a string.\n33: \u001B[34m    theme: \u001B[39m\n34: \u001B[34m      - light: flatly\u001B[39m\n            ~~~~~~~~~~~~~\n35: \u001B[34m      - dark: darkly\u001B[39m\n\u001B[31m✖\u001B[39m The value \u001B[34mlight: flatly\u001B[39m is object.\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mformat\u001B[39m:\u001B[34mhtml\u001B[39m:\u001B[34mtheme\u001B[39m:\u001B[34m0\u001B[39m.\n\n\nIn file _quarto.yml\n(line 35, columns 9--21) Array entry 2 with value \u001B[34mdark: darkly\u001B[39m failed to be a string.\n34: \u001B[34m      - light: flatly\u001B[39m\n35: \u001B[34m      - dark: darkly\u001B[39m\n            ~~~~~~~~~~~~\n36: \u001B[34m      - custom.scss\u001B[39m\n\u001B[31m✖\u001B[39m The value \u001B[34mdark: darkly\u001B[39m is object.\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mformat\u001B[39m:\u001B[34mhtml\u001B[39m:\u001B[34mtheme\u001B[39m:\u001B[34m1\u001B[39m.\n\n\nIn file _quarto.yml\n(line 34, columns 9--22) Array entry 1 with value \u001B[34mlight: flatly\u001B[39m failed to be a string.\n33: \u001B[34m    theme: \u001B[39m\n34: \u001B[34m      - light: flatly\u001B[39m\n            ~~~~~~~~~~~~~\n35: \u001B[34m      - dark: darkly\u001B[39m\n\u001B[31m✖\u001B[39m The value \u001B[34mlight: flatly\u001B[39m is object.\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mformat\u001B[39m:\u001B[34mhtml\u001B[39m:\u001B[34mtheme\u001B[39m:\u001B[34m0\u001B[39m.\n\n\nIn file _quarto.yml\n(line 35, columns 9--21) Array entry 2 with value \u001B[34mdark: darkly\u001B[39m failed to be a string.\n34: \u001B[34m      - light: flatly\u001B[39m\n35: \u001B[34m      - dark: darkly\u001B[39m\n            ~~~~~~~~~~~~\n36: \u001B[34m      - custom.scss\u001B[39m\n\u001B[31m✖\u001B[39m The value \u001B[34mdark: darkly\u001B[39m is object.\n\u001B[34mℹ\u001B[39m The error happened in location \u001B[34mformat\u001B[39m:\u001B[34mhtml\u001B[39m:\u001B[34mtheme\u001B[39m:\u001B[34m1\u001B[39m.\n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m19068\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m42833\u001B[0m:\u001B[0m\u001B[33m33\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///Applications/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m76757\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
